# automatically fetch contract sources from Etherscan
autofetch_sources: True
dotenv: .env

networks:
  default: development
  development:
    cmd_settings:
      mnemonic: brownie
      default_balance: 100000000000000000000
    update_interval: 60
    verify: False

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.5.0

compiler:
  evm_version: london
  solc:
    optimizer:
      enabled: true
      runs: 200
    remappings:
      - '@openzeppelin/contracts=OpenZeppelin/openzeppelin-contracts@4.5.0/contracts/'
      - '@chainlink/contracts=smartcontractkit/chainlink@1.13.0/contracts/'
    version: 0.8.12

console:
    show_colors: true
    color_style: monokai
    auto_suggest: true
    completions: true
    editing_mode: emacs